name: validate

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to test"
        required: true
        default: "STAGING"
        type: string
    secrets:
      notify_project_secret:
        description: "the notify project secret to use to test"
        required: true
      test_project_id:
        description: "the test project ID to use to test"
        required: true

jobs:
  validate-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run integration tests
        run: cargo test --test integration
        env:
          RUST_BACKTRACE: true
          ENVIRONMENT: ${{ inputs.environment }}
          NOTIFY_PROJECT_SECRET: ${{ secrets.notify_project_secret }}
          TEST_PROJECT_ID: ${{ secrets.test_project_id }}
